export default {
    BLACK: "#000000",
    WHITE: "#ffffff",
    THEME: "#2f7afa",
    THEME_TRANSPARENT: "#afcbfa",
    THEME_LIGHT: "#86b2fc",
    PLACEHOLDER: "#888888",
    FADE: "#e9e9e9",
    PAGE_COLOR: "#ececec",
    TRANSPARENT: "rgba(0,0,0,0.5)",
    DELETE: "#F2686F",
    SHOP_CARD: "#E9DEEC",
    RED: "#ff0000",
    ACTIVE_NAVIGATION_COLOR: "#006229",
    DISABLED_NAVIGATION_COLOR: "#808080",
    ICE_CREAM_TYPE: "#ffffff",
    ROW: "#eeeeee",
    TABLE_HEAD: "#6D7CD8",
    GRAY: "#4A545A",
    LIGHT_GRAY: "FAFAFA",
    TABLE_BORDER: "#E0E0E0",
    ROW_BORDER: "#EAEAEA",
    HEADER_BORDER: "#CCCCCC"
}